version: '3.1'

services:
    php:
        build: ./.docker/php
        volumes:
            - .:/var/www/html
            - ./.docker/php/pool.ini:/usr/local/etc/php-fpm.d/www.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - db
    nginx:
        build: ./.docker/nginx
        ports:
            - "8084:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    db:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=rootqwe123
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
